import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { CategoryProvider } from "../context/CategoryContext";
import "./globals.css";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} max-h-screen overflow-hidden`}>
        <div className="px-6 pt-2 mx-auto max-w-screen-lg">
          <Header />
          <CategoryProvider>
            <div className="flex min-h-screen flex-col">{children}</div>
          </CategoryProvider>
        </div>
      </body>
    </html>
  );
}
